name: Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - site/**

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo $GITHUB_REPOSITORY --pattern sitegen --pattern ronfmt
          chmod +x sitegen ronfmt
      - name: Validate
        run: |
          ./ronfmt site/_data/restaurants.ron
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: |
          ./sitegen ./site ./output
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "output"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
